#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
#printf "I ${RED}love${NC} Stack Overflow\n"
printf  "${YELLOW} sorting stack ....\n"
sleep 1
echo "testing with 3 random numbers"
printf "${NC}\n"
sleep 1
./push_swap $(./checker 3)
sleep 2
VAE=$(./push_swap $(./checker 3) | wc -l)

if [[ $VAE -ge 3 ]]; then
printf "${RED}"
printf "test failed ,${VAE} instructions!\n"
else
printf "${GREEN}"
printf "test succesed, ${VAE} instructions!!\n"
fi
sleep 3
printf "${YELLOW} testing with 5 random numbers\n"
printf "${NC}"
sleep 1
./push_swap $(./checker 5)
sleep 2
VAE=$(./push_swap $(./checker 5) | wc -l)

if [[ $VAE -ge 12 ]]; then
printf "${RED}"
printf "test failed ,${VAE} instructions!\n"
else
printf "${GREEN}"
printf "test succesed, ${VAE} instructions!!\n"
fi
sleep 3
echo "testing with 100 random number"
printf "${NC}"
sleep 1
./push_swap $(./checker 100)
sleep 2
VAE=$(./push_swap $(./checker 100) | wc -l)

if [[ $VAE -ge 500 ]]; then
printf "${RED}"
printf "test failed ,${VAE} instructions!\n"
else
printf "${GREEN}"
printf "test succesed, ${VAE} instructions!!\n"
fi
sleep 3
printf "${YELLOW} testing with 500 random number\n"
printf "${NC}"
sleep 1
./push_swap $(./checker 500)
sleep 2
VAE=$(./push_swap $(./checker 500) | wc -l)

if [[ $VAE -ge 700 ]]; then
printf "${RED}"
printf "test failed ,${VAE} instructions!\n"
else
printf "${GREEN}"
printf "test succesed, ${VAE} instructions!!\n"
fi